source ~/.config/profile

alias edit=$EDITOR

[[ -f ~/.localrc ]] && source ~/.localrc
[[ -f $XDG_CONFIG_HOME/zsh/localrc ]] && source $XDG_CONFIG_HOME/zsh/localrc
[[ -f $XDG_CONFIG_HOME/profile ]] && source $XDG_CONFIG_HOME/profile

warn()
{
	printf "\r\033[00;31m$*\033[0m\n"
}

ZSH=/usr/share/oh-my-zsh/
ZSH_CUSTOM=/usr/share/zsh
zstyle ':omz:update' mode disabled
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

plugins=(
	sudo
	copydir
	copyfile
	jsontools
	docker-compose
	zsh-autosuggestions
	zsh-syntax-highlighting
)
ENABLE_CORRECTION="true"
CORRECT_IGNORE_FILE='.*'

ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh
[[ -d $ZSH_CACHE_DIR ]] || mkdir $ZSH_CACHE_DIR
source "$ZSH/oh-my-zsh.sh"

setopt +o nomatch
setopt extended_glob

# Using custom configs at the end to override OMZ configs if needed.
for tf ($DOTFILES/*) if [[ -d $tf ]]; then fpath=($tf $fpath); fi;
for file in $DOTFILES/**/*.zsh; do
	source $file
done
