source ~/.config/profile

export -U PATH=$PATH

alias edit=$EDITOR

[[ -f ~/.localrc ]] && source ~/.localrc
[[ -f $XDG_CONFIG_HOME/zsh/localrc ]] && source $XDG_CONFIG_HOME/zsh/localrc
[[ -f $XDG_CONFIG_HOME/profile ]] && source $XDG_CONFIG_HOME/profile

warn()
{
	printf "\r\033[00;31m$*\033[0m\n"
}

# Autocompletion selection (tab highlight + arrow move)
zstyle ':completion:*' menu select

# ^Z when a job is suspended runs it in the background.
background()
{
	bg
}
zle -N background
bindkey ^Z background

# Use run-help to access zsh manuels
(whence -w run-help | grep -q alias) && unalias run-help
autoload run-help

function zvm_config()
{
	ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
	#ZVM_READKEY_ENGINE=$ZVM_READKEY_ENGINE_ZLE
}
function zvm_after_init()
{
	bindkey '^[[A' up-line-or-search
	bindkey '^[[B' down-line-or-search
	bindkey -M viins "^[[H" beginning-of-line
	bindkey -M viins  "^[[F" end-of-line
	bindkey -M vicmd "^[[H" beginning-of-line
	bindkey -M vicmd "^[[F" end-of-line
	bindkey -M visual "^[[H" beginning-of-line
	bindkey -M visual "^[[F" end-of-line
}

ZSH=/usr/share/oh-my-zsh/
ZSH_CUSTOM=/usr/share/zsh
zstyle ':omz:update' mode disabled
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

plugins=(
	zsh-vi-mode
	sudo
	copydir
	copyfile
	jsontools
	docker-compose
	zsh-autosuggestions
	zsh-syntax-highlighting
)
ENABLE_CORRECTION="true"
CORRECT_IGNORE_FILE='.*'

ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh
[[ -d $ZSH_CACHE_DIR ]] || mkdir $ZSH_CACHE_DIR
source "$ZSH/oh-my-zsh.sh"

mkdir -p $XDG_STATE_HOME/zsh
mkdir -p $XDG_CACHE_HOME/zsh
compinit -d $XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION
zstyle ':completion:*' cache-path $XDG_CACHE_HOME/zsh/zcompcache

setopt +o nomatch
setopt extended_glob


# Using custom configs at the end to override OMZ configs if needed.
for tf ($DOTFILES/*) if [[ -d $tf ]]; then fpath=($tf $fpath); fi;
for file in $DOTFILES/**/*.zsh; do
	source $file
done
