require "windows.toggleterm"
require "windows.which-key"
require "windows.telescope"
require "windows.trouble"
require "windows.scrollbar"
require "windows.colorcolumn"
require "windows.tree"
require "windows.harpoon"
require "windows.lualine"

