#!/usr/bin/env zsh

source ~/.config/profile
[[ -f ~/.config/Xresources ]] && xrdb -merge -I$HOME ~/.config/Xresources

devices=$(xinput list --name-only | grep -i touchpad || echo "")
for device in $devices; do
	xinput set-prop $device "libinput Tapping Enabled" 1
	xinput set-prop $device "libinput Natural Scrolling Enabled" 1
done

# TODO move this out of here, this should not be defined like that nor pushed
xrandr --output HDMI-0 --primary --auto --output DVI-D-0 --auto --right-of HDMI-0 --output DP-0 --auto --left-of HDMI-0
setxkbmap -option caps:escape
xmodmap ~/.config/Xmodmap

xset +fp $XDG_DATA_HOME/fonts
xset fp rehash

xset s off -dpms
xss-lock lock &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
dbus-update-activation-environment --systemd DISPLAY

picom -b > /dev/null 2>&1
source $DOTFILES/cli/zsh/alias.zsh
wp &
dwmblocks &
sxhkd &
clipmenud &
dunstctl set-paused true
fcitx5 -d

# I start the session via LightDM with auto-logging and here we show the lockscreen and wait for the password to unlock both the session and the gnome-keyring.
lock -n
discord &
redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | awk 'OFS=":" {print $3,$5}' | tr -d ',}') &

while true; do
	source ~/wm # A file to define the window manager to use. I use this to easilly switch between dwn and xmonad while the config is not done
	${WM:-dwm}
done
