#!/usr/bin/env zsh
set -e

source ~/.config/profile

[[ -f ~/.config/Xresources ]] && xrdb -merge -I$HOME ~/.config/Xresources

devices=$(xinput list --name-only | grep -i touchpad || echo "")
for device in $devices; do
	xinput set-prop $device "libinput Tapping Enabled" 1
	xinput set-prop $device "libinput Natural Scrolling Enabled" 1
done

# TODO move this out of here, this should not be defined like that nor pushed
xrandr --output HDMI-0 --primary --auto --output DVI-D-0 --auto --right-of HDMI-0 --output DP-0 --auto --left-of HDMI-0
setxkbmap fr

xset +fp $XDG_DATA_HOME/fonts
xset fp rehash

xset s off -dpms
xss-lock lock &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
dbus-update-activation-environment --systemd DISPLAY

picom -b
feh --no-fehbg --bg-center --recursive --randomize ~/.wallpapers &
dwmblocks &
sxhkd &
clipmenud &
redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | awk 'OFS=":" {print $3,$5}' | tr -d ',}') &

{ source $DOTFILES/rofi/todo.zsh && todogit pull || true } &

discord > /dev/null 2>&1 &!

while true; do
	dwm
done
