#!/usr/bin/env zsh
set -e

source ~/.profile

devices=$(xinput list --name-only | grep -i touchpad || echo "")
for device in $devices; do
	xinput set-prop $device "libinput Tapping Enabled" 1
	xinput set-prop $device "libinput Natural Scrolling Enabled" 1
done

# TODO move this out of here, this should not be defined like that nor pushed
xrandr --output HDMI-0 --primary --auto --output DVI-D-0 --auto --right-of HDMI-0 --output DP-0 --auto --left-of HDMI-0
setxkbmap fr
setxkbmap -option caps:swapescape

xset +fp ~/.fonts
xset fp rehash

xset s off -dpms
xss-lock lock &

/usr/lib/polkit-kde-authentication-agent-1 &

export $(dbus-launch)

picom -b
feh --no-fehbg --bg-center --recursive --randomize ~/.wallpapers &
dwmblocks &
sxhkd &
dunst & 
clipmenud &
redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | awk 'OFS=":" {print $3,$5}' | tr -d ',}') &

discord > /dev/null 2>&1 &!

while true; do
	dwm
done
